### ISSUE TITLE
yiddish needs internet access to run

### ISSUE THREAD

**Issue by jacobjwebber** [ibleaman/yiddish-text-tools#4]
Tagging @dan-wells who spotted this

https://github.com/ibleaman/yiddish/blob/master/yiddish/yiddish.py#L70
There is a download which runs every time the script is invoked.

This causes problems when the internet isn't available. There are a couple of possible fixes -- 
1) downloading once and caching somewhere sensible, 
2) including this file as part of the yiddish pip package.

**Comment by jacobjwebber** [comment]
I can submit a PR if you want me too!

**Comment by ibleaman** [comment]
@jacobjwebber @dan-wells Thanks, I'll take care of this very soon! It has long been on my to-do list.

**Comment by ibleaman** [comment]
As of v0.0.15, `pip install yiddish` now includes all the data files needed to use the package. This means that `import yiddish` does not require internet access.

If you're curious: I initially tried to include [this repo](https://github.com/ibleaman/loshn-koydesh-pronunciation) and [this other repo](https://github.com/ibleaman/hasidify_lexicon) as git submodules, but those were not correctly being included in the package builds (the submodule folders were ostensibly empty and thus not being pushed to PyPI). Instead, I've resolved this by using a GitHub Action to clone the latest version of those repositories to `yiddish/submodules`, which are then included in the package build because their `.txt` and `.csv` files are named in `MANIFEST.in`.
